version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      -  ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - ./data:/data/db
  
  backend:
    build: ./backend
    restart: always
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    environment:
      - MONGO_URI=${MONGO_URI}
  
  frontend:
    build: ./frontend
    restart: always
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
