version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  
  backend:
    build: ./backend
    restart: always
    ports:
      - 3000:3000
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase
  
  frontend:
    build: ./frontend
    restart: always
    ports:
      - 5173:5173
