name: ESLint Check

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies and run ESLint on Frontend
      run: |
        cd frontend
        npm install
        npm run lint
      shell: bash
      
    - name: Install dependencies and run ESLint on Backend
      run: |
        cd backend
        npm install
        npm run lint
      shell: bash

